M48
; DRILL file {KiCad 7.0.10} date Sun Apr 14 19:08:22 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-14T19:08:22+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0402
%
G90
G05
T1
X0.76Y-0.605
X0.76Y-0.9593
X1.8057Y-1.85
X2.16Y-1.85
X2.3069Y-1.852
X2.6612Y-1.852
M30
